title: Sahil Arora
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    title: Sahil Arora
    tagline: Student
    profile_img: >-
      https://res.cloudinary.com/practicaldev/image/fetch/s--Kfqqn1Ub--/c_fill,f_auto,fl_progressive,h_320,q_auto,w_320/https://dev-to-uploads.s3.amazonaws.com/uploads/user/profile_image/360673/43c17893-f0d8-4984-9467-19581c1e0b44.png
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Blog
        url: /blog/
        style: link
      - label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - label: GitHub
        url: 'https://github.com/sahilarora3117'
        style: icon
        icon_class: github
        new_window: true
      - label: DEV
        url: 'https://dev.to/sahilarora3117'
        style: icon
        icon_class: dev
        new_window: true
  footer:
    content: >-
    links:
      - label: Github
        url: 'https://github.com/sahilarora3117'
        new_window: true
        style: link
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
